### ISSUE TITLE
Libraries and newlines in js

### ISSUE THREAD

**Issue by esteban-turnocheck** [jaxon-php/jaxon-dialogs#1]
Hi!
I found a new little issue that was causing the modal dialog not showing up.
I'm using jaxson v2.x & dialogs plugin.
In line 61 of Libraries/PgwjS/Plugin.php it says, for the registration of the command handler:
```
    // Set user and default options into data only when they are missing
    for(key in sweetAlertOptions)
    {

```

When that is printed in the browser, however, it's printed without the newlines, so everything becomes a js comment in a single line.
Now, that might be an issue only some systems. I didn't give it much thought, but thinking in newline differences between windows/linux (i'm on ubuntu). I just had to take away the comment, but first tried adding a 

> ' . "\r\n" . '

but didn't have any effect.
I believe the same issue is happening in Libraries/SweetAlert/Plugin.php

Thanks!

**Comment by feuzeu** [comment]
Hi,
Have you enabled the js code minifier? In this case, try setting the `js.app.minify` option to false.
Some issues have been reported with the minifier Jaxon is currently using.

**Comment by esteban-turnocheck** [comment]
Hi.
Actually, i have that option already set to false, as for the other issue i report (https://github.com/jaxon-php/jaxon-js/issues/3) (to be able to debug the jaxon.js and patch that)
'Eating up' the newlines seems to me like a strange behaviour, but doesn't look like it is the minifier.

**Comment by feuzeu** [comment]
Is the Jaxon js code exported into an external file or included in your HTML code?

**Comment by esteban-turnocheck** [comment]
If you are talking about the `'js.app.extern' => true,`, then i've just tried both ways before writing this message.
The output, (in both cases embedded in the html, by the way, may be i'm doing something wrong?), is this, as copied from the "View page source" on Chrome. (I've tested in firefox too)
```
var pgwModalUserOptions = {};
jaxon.command.handler.register("pgwModal", function(args) { // Set user and default options into data only when they are missing for(key in pgwModalUserOptions) { if(!(key in args.data)) { args.data[key] = pgwModalUserOptions[key]; } } for(key in pgwModalDefaultOptions) { if(!(key in args.data)) { args.data[key] = pgwModalDefaultOptions[key]; } } $.pgwModal(args.data);
});

```

It's clearly visible that there are no newlines and everything inside the function gets commented out.

**Comment by feuzeu** [comment]
If the dir indicated by the `js.app.dir` option does not exist, the Jaxon code is embedded in the HTML code even if the `js.app.extern` option is set to true.

Regarding the issue, another usual suspect is the webserver. Check if it does not apply any filter to the code before it is sent back to the browser.
