### ISSUE TITLE
Update JQuery-Confirm to 3.3.0 version

### ISSUE THREAD

**Issue by jatubio** [jaxon-php/jaxon-dialogs#3]
Hello,

Firstly thank you for this plugin that is very useful and, above all, very complete for the possibility of using so many libraries! Good Work! :+1: 

I'm using Bootstrap 4 and JQuery-Confirm have upgraded to 3.3.0 version to be compatible. I have hacked your code to use them, but i will be nice to have this last version without the hack :wink: 

Thank you

**Comment by jatubio** [comment]
Solved (https://github.com/jaxon-php/jaxon-dialogs/pull/4#issuecomment-326796556)

**Comment by feuzeu** [comment]
Starting from the `1.1.0` release, a different version number on CDN can be chosen by configuration for each javascript library.
There's an example in the `Configuration` section of the README.
