### ISSUE TITLE
Jaxon Dialogs with form in modal window

### ISSUE THREAD

**Issue by mbabini** [jaxon-php/jaxon-dialogs#5]
Hi Thierry

Many thanks for your hard work on Jaxon and Dialogs for Jaxon!!

I'm trying to move from Xajax to Jaxon. With Xajax, I have used the Modal Window Plugin provided by Xajax for different modal windows which contain forms. Since it seems that the modal window plugin from Xajax was not ported to Jaxon, I try to get things work with the Jaxon Dialogs plugin.

I have a two questions concerning forms inside of a modal window:
(1) Is it possible to use the API of the used library - i.e. jconfirm?
`$xResponse->script('jconfirm.setTitle("This is my new title");');`
does not work (jconfirm.setTitle is not a function)
(2) How can I show a modal window with zero buttons? If I just use
`$xResponse->dialog->show($title, $content, array(), $options);`
I get two default buttons (OK and Cancel).

Many thanks for your help!
Michelle

**Comment by feuzeu** [comment]
Hi Michelle,

I'm glad you find the Jaxon library useful. It's always a pleasure to hear about Jaxon users.

You can call any JQueryConfirm function as any other js function with the `$xResponse->script()` method. But you need to make the call with the variable the JQueryConfirm dialog is stored in, which in this case is `jaxon.dialogs.jconfirm.dialog`. So after calling `$xResponse->dialog->show();`, make a call to `$xResponse->script('jaxon.dialogs.jconfirm.dialog.setTitle("This is my new title");');` to set a new title on the dialog.

The `$.dialog()` function of the JQueryConfirm library doesn't display any button. Therefore,  to show dialogs, I had to use the `$.confirm()` function, which displays default buttons when no button is provided.
They fixed the issue in their 3.3.1 release. You'll then need to use a more recent version of the library, by setting the following options:

- dialogs.jconfirm.uri: https://cdnjs.cloudflare.com
- dialogs.jconfirm.subdir: ajax/libs/jquery-confirm
- dialogs.jconfirm.version: 3.3.2

**Comment by feuzeu** [comment]
Hi,
Can I close this issue?
Thierry

**Comment by mbabini** [comment]
Hi Thierry

Please excuse me for not reporting until now.
Thank you for your helpful answers! Everything works fine with your tips.

Best regards
Michelle
