### ISSUE TITLE
Feature request: add Keyboard events for buttons (jconfirm)

### ISSUE THREAD

**Issue by mbabini** [jaxon-php/jaxon-dialogs#6]
Hi Thierry

I'm using your jaxon dialogs script with jconfirm. In my use case with forms inside of modal windows, it would be important for the usability to be able to submit the form using the "Enter" key. jconfirm does offer the possibility to add keyboard events to each button, but as far as I can see, there is currently no way to use keyboard events with jaxon dialogs...

I've tried to integrate a fourth element to the buttons array:
```
$buttons[] = array(
  'title' =>'Submit', 
  'class' => 'btn btn-blue',
  'keys' => array('enter', 'shift'),
  'click' => "JaxonModalClass.mySubmitFunction(jaxon.getFormValues('form_name')); return false;"
);
```

And alter the show function in jaxon-dialogs/src/Libraries/JQueryConfirm/Plugin.php as follows:
```
public function show($title, $content, array $buttons, array $options = array())
{
    $options['title'] = (string)$title;
    $options['content'] = (string)$content;
    $options['buttons'] = array();
    if(!array_key_exists('boxWidth', $options))
    {
        $options['useBootstrap'] = false;
        $options['boxWidth'] = '600';
    }
    $ind = 0;
    foreach($buttons as $button)
    {
        // START OF PATCH!!!
        /*$options['buttons']['btn' . $ind++] = array(
            'text' => $button['title'],
            'btnClass' => $button['class'],
            'action' => $button['click'],
        );*/
        $options['buttons']['btn' . $ind] = array(
            'text' => $button['title'],
            'btnClass' => $button['class'],
            'action' => $button['click'],
        );
        if (array_key_exists('keys', $button) && !empty($button['keys'])) {
          $options['buttons']['btn' . $ind]['keys'] = $button['keys'];
        }
        $ind++;
        // ENDE OF PATCH!!!
    }
    // Show dialog
    $this->addCommand(array('cmd' => 'jconfirm.show'), $options);
}
```
This seems to work fine for the "shift" key, **but unfortunately not for the "enter" key!** Every time enter is pressed, the whole browser tab is reloaded instead of submitting the form. Perhaps you can give me a hint?

Feel free to integrate my little patch if you are interested...

Many thanks for your support and best regards
Michelle

**Comment by mbabini** [comment]
Hi

In the meantime, I've found a jQuery-only solution:

1. add a special class to the button that should react on Enter:
```
$buttons[] = array(
  'title' =>'Submit', 
  'class' => 'btn btn-blue enter-key-submit-class',
  'click' => "JaxonModalClass.mySubmitFunction(jaxon.getFormValues('form_name')); return false;"
);
```
2. add this code to the onload function:
```
$('body').on('keypress', '.jconfirm-content :input', function(event) {
  if (event.keyCode == 13) {
    event.preventDefault();
    $('.enter-key-submit-class').trigger('click');
  }
});

This seems to work without any patch.

**Comment by feuzeu** [comment]
Dialog buttons now accept additional attributes.
